services:
  # Netdata: Real-time performance monitoring
  netdata:
    image: netdata/netdata:v1.44.2  # System metrics and monitoring
    container_name: netdata
    ports:
      - "19999:19999"
    hostname: coder.hungngquang.xzy
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - ./cloud.conf:/var/lib/netdata/cloud.d/cloud.conf:ro
    restart: unless-stopped

  # Coder: Remote development platform
  coder:
    image: ghcr.io/coder/coder:v2.25.1  # Remote development server
    container_name: coder
    ports:
      - "3000:3000"
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@coder_database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_ACCESS_URL: "https://coder.hungngquang.xyz"
      CODER_WILDCARD_ACCESS_URL: "*.hungngquang.xyz"
      CODER_HTTP_ADDRESS: "0.0.0.0:3000"
      CODER_TLS_ENABLE: "false"
      CODER_TLS_REDIRECT_HTTP: "false"
      CODER_DANGEROUS_ALLOW_PATH_APP_SHARING: "true"
      CODER_PROMETHEUS_ENABLE: "true"
      CODER_PROMETHEUS_ADDRESS: "0.0.0.0:2112"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/certs:/etc/ssl/certs:ro
    # Add Docker group permissions
    group_add:
      - ${DOCKER_GROUP_ID}
    restart: unless-stopped
    depends_on:
      coder_database:
        condition: service_healthy

  # Cloudflare Tunnel: Securely expose local services to the internet
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    network_mode: "service:coder"
    restart: unless-stopped
    depends_on:
      - coder

  # PostgreSQL: Database for Coder
  coder_database:
    image: "postgres:16.2"  # Latest stable PostgreSQL
    container_name: coder-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-coder}
    volumes:
      - coder_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# Persistent storage volumes
volumes:
  coder_data:        # Stores PostgreSQL database files
  netdataconfig:     # Stores Netdata configuration
  netdatalib:        # Stores Netdata database
  netdatacache:      # Stores Netdata cache
